name: XML TEI unifier
on: [push]
jobs:
  unifier:
    runs-on: ubuntu-22.04
    steps:
      - run: |
         echo "Installining xqilla..."
         sudo apt-get update
         sudo apt-get install xqilla

      - uses: actions/checkout@v4

      - run: |
         echo "Generating the index file..."
         echo "<files>" > a.xml
         find xml -type f | sort -u | grep xml$ | while read LINE; do
           echo "<file>$LINE</file>" >> a.xml
         done
         echo "</files>" >> a.xml

      - run: |
         echo "Unifying files..."
         cp scripts/unifier.xql .
         xqilla unifier.xql > output.xml

      - uses: actions/upload-artifact@v4
        with:
          name: XML-TEI
          path: output.xml
